# Generated by Django 2.1.3 on 2018-11-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181117_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Store')),
            ],
        ),
    ]
