# Generated by Django 2.1.3 on 2018-11-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='store',
        ),
    ]
