# Generated by Django 2.1.3 on 2018-11-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_item_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rests',
            new_name='Rest',
        ),
    ]
