# Generated by Django 2.1.3 on 2018-11-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181117_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
